In [1]:
from merge_dna.models.token_merge import TokenMergeDummy, TokenMerge
from merge_dna.models.unmerge import UnmergeDummy
import torch

In [4]:
x = torch.rand(3, 7, 2)
k = torch.rand(3, 7, 2)
merger = TokenMerge(2, protect_cls=False)
merged, source_index = merger(x, k)
print(x.shape)
print()
print(k.shape) 
print()
print(merged.shape)
print()
print(source_index)

tensor([[0.9765, 0.9870, 0.9933, 0.9821],
        [0.9777, 0.9886, 0.9649, 0.9691],
        [0.9923, 0.9799, 0.9964, 0.9979]]) tensor([[2, 2, 2, 0],
        [0, 0, 2, 0],
        [2, 1, 0, 1]])
torch.Size([3, 4])
dst_idx: tensor([[2, 2],
        [0, 0],
        [1, 0]])
torch.Size([3, 7, 2])

torch.Size([3, 7, 2])

torch.Size([3, 5, 2])

tensor([[0, 2, 4, 3, 4, 4, 1],
        [2, 2, 2, 3, 0, 4, 1],
        [0, 2, 1, 3, 2, 4, 3]])


In [3]:
merger._unm_idx

tensor([[2],
        [2],
        [0]])

In [ ]:
merger = TokenMergeDummy(merge_factor=4)
B, L, D = 2, 12, 8
x = torch.randn(B, L, D)
merged, source_index = merger(x)
print(merged.shape, source_index)

torch.Size([2, 3, 8]) tensor([[0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2],
        [0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]])


In [ ]:
unmerge = UnmergeDummy()
unmerged = unmerge(merged, source_index)
unmerged.shape

torch.Size([2, 12, 8])